{% set version = "0.13.0" %}

package:
  name: poliastro
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/poliastro/poliastro/archive/v{{ version }}.tar.gz
  md5: 9b1c416a28ace5633ffd54a8d0aaaf09

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip

  run:
    - python >=3.5
    - numpy >=1.9
    - scipy >=1.0
    - numba >=0.39
    - astropy >=3.2,<4
    - jplephem
    - matplotlib-base >=2.0,!=3.0.1
    - pandas
    - plotly >=4.0,<5
    - requests
    - beautifulsoup4
    - astroquery >=0.3.9
    - notebook
    - ipywidgets >=7.0

test:
  imports:
    - poliastro
    - poliastro.constants
    - poliastro.coordinates
    - poliastro.twobody
    - poliastro.threebody
    - poliastro.iod
    - poliastro.frames
    - poliastro.plotting

  requires:
    - pytest

about:
  home: https://poliastro.github.io/
  license: MIT
  summary: "Python package for Orbital Mechanics"

extra:
  recipe-maintainers:
    - juanlu001
